### ISSUE TITLE
gl wrapper

### ISSUE THREAD

**Issue by nikolads** [d3lio/BattleTanks#4]
Create wrapper classes around the most used OpenGL functions and objects
- [x] shader and program
- [x] vao
- [x] vbo
- [x] attribute and uniform locations
- [x] texture

and anything else we see a need for

**Comment by d3lio** [comment]
The VAO needs some more polishing since it can be bound after creation of VBOs, unless we want to allow this behaviour.
See vao_vbo branch.

**Comment by d3lio** [comment]
VAO doen't manage it's own VBOs anymore.

**Comment by d3lio** [comment]
Added texture to the list. I'll work on it since it's necessary for the shader loader/builder.

**Comment by nikolads** [comment]
Added vertex attributes and uniforms.
